czech_education:
  target: dev
  outputs:
    dev:
      type: trino
      host: localhost
      port: 8080
      user: admin
      catalog: iceberg
      schema: testnamespace
      session_properties:
        query_max_run_time: 10m